[package]
name = "manifest"
version = "0.1.0"
authors = ["rumblefrog <contact@rumblefrog.me>"]
edition = "2018"

[lib]
name = "manifest"
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
