name = "edge-worker"
type = "rust"
account_id = "5579056547b22d74a491ac1a86825107"
route = "sourcemod.dev/*"
zone_id = "c00ac38895ec0c75754843adbebfd3e1"

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"
