[package]
name = "mono"
version = "1.0.0"
authors = ["rumblefrog <contact@rumblefrog.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
spdcp = { version = "0.4.4", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
