name: Build DocGen

on: [push]

jobs:
  library:
    name: SP Libraries

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1

      - name: Checkout generator
        uses: actions/checkout@v2

      - name: Checkout SourcePawn
        uses: actions/checkout@v2
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        with:
          repository: alliedmodders/sourcepawn
        